name: Build and Deploy Next.js App to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Next.js App
        run: npm run build

      - name: Prepare Deployment Package
        run: |
          mkdir deploy
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/
          cp -r public deploy/public || true
          cp package.json deploy/
          cd deploy && npm install --omit=dev --legacy-peer-deps

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: thisisthenextjsapp  
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deploy
